{% set name = "pytest-mypy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e284a2e8d27bc16a3069c34ab601b2f48fceba9bd435d65f69b7d8f41c373d6e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools_scm >=7.1
    - wheel >=0.40
  run:
    - attrs >=19.0
    - filelock >=3.0
    - mypy >=0.50
    - pytest >=4.6
    - python >={{ python_min }}

test:
  source_files:
    - pyproject.toml
    - tests
  requires:
    - pip
    - mypy
    - pytest >=4.6
    - packaging
    - pexpect
    - pytest-cov
    - pytest-randomly
    - pytest-xdist
    - python {{ python_min }}
  commands:
    - pip check
    - pytest -p no:mypy tests
  imports:
    - pytest_mypy

about:
  home: https://github.com/dbader/pytest-mypy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mypy static type checker plugin for Pytest
  doc_url: https://pypi.org/project/pytest-mypy/
  dev_url: https://github.com/dbader/pytest-mypy

extra:
  recipe-maintainers:
    - sduc
