{% set name = "pytest-mypy" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8458f642323f13a2ca3e2e61509f7767966b527b4d8adccd5032c3e7b4fd3db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=61.0
    - setuptools_scm >=7.1
    - wheel >=0.40
  run:
    - attrs >=19.0
    - filelock >=3.0
    - mypy >=0.50
    - pytest >=4.6
    - python >=3.6

test:
  source_files:
    - pyproject.toml
    - tests
  requires:
    - pip
    - mypy
    - pytest >=4.6
    - packaging
    - pexpect
    - pytest-cov
    - pytest-randomly
    - pytest-xdist
  commands:
    - pip check
    - pytest -p no:mypy tests
  imports:
    - pytest_mypy

about:
  home: https://github.com/dbader/pytest-mypy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mypy static type checker plugin for Pytest
  doc_url: https://pypi.org/project/pytest-mypy/
  dev_url: https://github.com/dbader/pytest-mypy

extra:
  recipe-maintainers:
    - sduc
